#!/bin/bash

echo 'Removing "nginx-custom" Docker Container...'
docker container rm -f nginx-custom
echo '"nginx-custom" Docker Container removed successfully!'

echo 'Launching new "nginx-custom" container...'
docker run --name nginx-custom -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf -d -p 8080:8080 nginx:latest nginx-debug -g 'daemon off;'

echo 'Check the container status:'
echo ''
docker ps | grep COMMAND
docker ps -a | grep nginx-custom  
echo ''
docker logs nginx-custom
